training:
  batch_size: 32
  shuffle: true
  learning_rate: 0.001
  num_epochs: 2
  device: "cpu"

model:
  num_tokens: 20
  embedding_dim: 128
  num_layers: 6
  num_heads: 8
  dropout: 0.1

data:
  train_split: 0.8
  val_split: 0.2
  random_seed: 2116
  dataset_path: "curriculum_data.csv"

logging:
  log_dir: "logs/tensorboard"